### ISSUE TITLE
Contribute new locale

### ISSUE THREAD

**Issue by moswed** [Nurrl/Duckuino#82]
hi @Nurrl 

since you closed pull requests for the https://github.com/Nurrl/LocaleKeyboard.js repo, where can i put my created .lang file so it gets added to your converter? :)

**Comment by Nurrl** [comment]
Hi @moswed, in order to create a new locale for the next version, you need to be on the v2.1 branch and look how I made others, it's very straight forward, but if you have any issue, please let me know :)
You'll need to place it in `modules/arduino/locales/`.
Thanks for you involvement in the project by the way :)

**Comment by moswed** [comment]
somehow i missed your answer to this, sorry ;)
will include my created file asap and make a pull request.

And thank YOU for this nice project 💃 

hope to see the locale gets added to offical malduino script converter :)
